### PR TITLE
Add basic auth to fetch_dataset

### PR DESCRIPTION
**Pull request by mrmattwilkins**
Some timeseries are password protected.  This adds basicauth to the fetch_dataset method.

### CODE REVIEW

**Review by kinverarity1 — CHANGES_REQUESTED** [review]
Thanks for the feedback and PR!

Could you please change this to instead add **kwargs to the method call and requests.get call, that would be better as it's much more flexible than the present suggestion?

e.g.

image

and

image

Then you can use basic auth with ``fetch_dataset(..., auth=("user", "pwd"))``

**Comment by mrmattwilkins** [comment]
Does that mean the credentials will be in the url though?

**Comment by kinverarity1** [comment]
Yep you're right, I've put in a separate PR #4 to allow use of a custom session with

```
s = requests.Session()
s.auth = user, pwd
aq = aquarius_webportal.AquariusWebPortal(session=s)
```

**Comment by mrmattwilkins** [comment]
Cool, good stuff.

**Pull request closed without merging**
